/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin application project to get you started.
 */

import org.jetbrains.kotlin.gradle.tasks.KotlinCompile

plugins {
    // Apply the Kotlin JVM plugin to add support for Kotlin.
    id("org.jetbrains.kotlin.jvm") version "1.3.72"

    // Apply the application plugin to add support for building a CLI application.
    application
}

repositories {
    // Use jcenter for resolving dependencies.
    // You can declare any Maven/Ivy/file repository here.
    jcenter()
}

dependencies {
    // Align versions of all Kotlin components
    implementation(platform("org.jetbrains.kotlin:kotlin-bom"))

    // Use the Kotlin JDK 8 standard library.
    implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk8")

    //Javalin.
    implementation("io.javalin:javalin:3.10.1")

    //Koin
    implementation("com.google.inject:guice:4.2.0")
    implementation("com.google.inject.extensions:guice-multibindings:4.2.0")

    //Jsckson
    implementation("com.fasterxml.jackson.core:jackson-databind:2.10.3")

    //Sl4j
    implementation("org.slf4j:slf4j-api:1.8.0-beta4")
    implementation("org.slf4j:slf4j-simple:1.8.0-beta4")

    //Redis
    implementation("io.vertx:vertx-redis-client:3.9.3")

    //Mongo
    implementation("org.litote.kmongo:kmongo:4.1.2")

    // Use the Kotlin test library.
    testImplementation("org.jetbrains.kotlin:kotlin-test")

    // Use the Kotlin JUnit integration.
    testImplementation("org.jetbrains.kotlin:kotlin-test-junit")

    // Use the Kotlin JUnit integration.
    testImplementation("org.jetbrains.kotlin:kotlin-test-junit")

    // Mockito.
    testImplementation("org.mockito:mockito-core:3.3.3")
}

application {
    // Define the main class for the application.
    mainClassName = "com.sample.AppKt"
}

tasks.withType<KotlinCompile>().configureEach {
    kotlinOptions.jvmTarget = "1.8"
}