/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.sample

import kotlin.test.Test
import kotlin.test.assertNotNull
import kotlin.test.assertEquals
import org.mockito.Mockito

class AppTest {
    @Test fun testObterTodos() {
        val alunoController = Mockito.mock(AlunoController::class.java)
        Mockito.`when`(alunoController.obterTodosAlunos()).thenReturn(mutableListOf(Aluno("Tiago", 30, "111"), Aluno("Taynara", 32, "222")))
        val alunos = alunoController.obterTodosAlunos()
        assertEquals(alunos.size, 2, "O tamanho não é 2")
    }
}
